name: Comix Downloader

on:
  workflow_dispatch:
    inputs:
      manga_url:
        description: "Comix manga URL"
        required: true

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run downloader
        run: |
          python downloader.py "${{ github.event.inputs.manga_url }}"

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: manga
          path: output/*.zip
